import type { NextPage } from 'next';
import Head from 'next/head';
import { IProject } from '../../collection';
import { Background, Container, Header, ProjectList } from '../../components';

interface Props {
  projects: IProject[];
}

const Projects: NextPage<Props> = ({ projects }) => {
  return (
    <Background>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="mt-12">
        <Container>
          <ProjectList projects={projects} />
        </Container>
      </main>
    </Background>
  );
};

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('https://web-cam-gules.vercel.app/api/project');
  // const res = await fetch('http://localhost:3000/api/project?page=1');

  const { data } = await res.json();

  console.log('data', data);
  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      projects: data,
    },
  };
}

export default Projects;
