import type { NextPage } from 'next';
import Head from 'next/head';
import { Background, Container, Header, ProjectList } from '../../components';

const Projects: NextPage = ({ projects }: any) => {
  return (
    <Background>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className='mt-12'>
        <Container>
          <ProjectList projects={projects} />
        </Container>
      </main>

    </Background>
  );
};

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('http://localhost:3000/api/home');
  const { data } = await res.json();

  const { projects } = data;

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      projects,
    },
  };
}

export default Projects;
