import type { NextPage } from 'next';
import Head from 'next/head';
import {
  Background,
  Container,
  Header,
  Title,
  Text,
  Socials,
} from '../components';

interface Props {
  title: string;
}
function AboutBlock({ title }: Props) {
  return (
    <div className="grid grid-cols-3 gap-6">
      <div className="col-start-2 flex items-center text-4xl">
        <Text>{title}</Text>
      </div>
      <div>
        <ul className="grid gap-4">
          <li>
            <Text>Design internship | Phibious (Vietnam)</Text>
          </li>
          <li>
            <Text>Graphic designer | ANTS (Vietnam)</Text>
          </li>

          <li>
            <Text>
              Freelance design | brand identity, packaging and interactive
              design
            </Text>
          </li>
        </ul>
        <Text>dadsds</Text>
      </div>
    </div>
  );
}

const About: NextPage = () => {
  return (
    <Background>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Container>
        <div className="text-6xl">
          <Title level="1">Hey, this is cam.</Title>
          <div className="grid grid-cols-10">
            <div className="col-start-2 col-end-10">
              <Title level="3">
                I am an art director, a graphic designer with experience of
                working with both local & global clients and agencies.
              </Title>
            </div>
          </div>
        </div>

        <div className="grid gap-16">
          <AboutBlock title="Experience" />
          <AboutBlock title="Recognition" />
        </div>

        <div>
          <div>
            <Text>
              Wanna talk?
              <br /> You know where to find me.
            </Text>
          </div>
          <div className="flex justify-between items-center">
            <div className="flex gap-4">
              <Socials />
            </div>
            <Text>@{new Date().getFullYear()}</Text>
          </div>
        </div>
      </Container>
    </Background>
  );
};

export default About;
