import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import {
  Background,
  Button,
  Container,
  Logo,
  ProjectList,
  Socials,
  Text,
  ToggleTheme,
} from '../components';

const Home: NextPage = () => {
  return (
    <Background>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <Container>
            <div className="grid items-center  min-h-screen">
              <Logo />
              <div className="text-dark dark:text-white text-7xl">
                <div>Cam</div>
                <div className="font-semibold">art director</div>
                <div>saigon, vietnam.</div>
              </div>

              <div>
                <div className="mb-6">
                  <Text>Wanna talk? You know where to find me.</Text>
                </div>

                <div className="flex gap-4 justify-between">
                  <div className="flex gap-4">
                    <Socials />
                  </div>

                  <ToggleTheme>
                    <Button>
                      <span>Light it</span>
                    </Button>
                  </ToggleTheme>
                </div>
              </div>
            </div>
          </Container>
        </div>

        <Container>
          <ProjectList projects={Array.from(Array(3).keys())} />

          <div className="mt-16">
            <Link href="/projects">
              <a>
                <Button>
                  <span>See all my projects</span>
                </Button>
              </a>
            </Link>
          </div>
        </Container>
      </main>
    </Background>
  );
};

export default Home;
