import type { NextPage } from 'next';
import Head from 'next/head';
import { Background, Container, Header, ProjectList } from '../components';

const Projects: NextPage = () => {
  const projects = Array.from(Array(10).keys());
  return (
    <Background>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Container>
        <ProjectList projects={projects} />
      </Container>
    </Background>
  );
};

export default Projects;
